version: '3.8'
services:
    java-maven-app: 
      image: gpenieljacobpaul/docker-java-maven-app:${IMAGES}
      ports:
        - 8080:8080
    postgres:
      image: postgres:13
      ports:
        - 5432:5432
      environment:
        - POSTRESS_PASSWORD=my-pwd